modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="nebs" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Neko’s Enchanted Books" #mandatory
authors="Nekomaster, CGessinger" #optional
description='''A small mod that adds unique textures to every Enchanted Book in vanilla Minecraft, in addition to every book in the mods...
- Ensorcellation
- Veinmining
- Charm
- Wall-Jump!
- Apotheosis
- Jellyfishing
- VanillaTweaks
- BetterDefaultBiomes
- Wonderful Enchantments
- Shulker Enchantments
- Step, Leap, Dash
- Farmer's Delight
- Alex's Mobs
- Allurement
- Momentum
- Elenai Dodge 2
- Advent of Ascension 3
- Greed N' Bleed
- Create
- Corpse Complex
- BetterEnd (Forge)
'''

[[dependencies.nebs]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.4,1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.nebs]]
    modId="wonderful_enchantments"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="CLIENT"

[[dependencies.nebs]]
    modId="inspirations"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="BEFORE"
    side="CLIENT"